# Generated by Django 4.1 on 2023-04-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_auther_post_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="create",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="update",
            new_name="updated",
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("DF", "Draft"), ("PB", "Published")],
                default="DF",
                max_length=2,
            ),
        ),
    ]
