# Generated by Django 4.1 on 2023-06-05 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_comments"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments",
            old_name="activate",
            new_name="active",
        ),
        migrations.RenameField(
            model_name="comments",
            old_name="emai",
            new_name="email",
        ),
    ]
